
package com.zdsoft.webservice.namespace.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://webservice.zdsoft.com/namespace/userservice")

public interface IUserService {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "info", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.zdsoft.com/namespace/userservice", className = "com.zdsoft.webservice.namespace.userservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.zdsoft.com/namespace/userservice", className = "com.zdsoft.webservice.namespace.userservice.LoginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param username
     * @return
     *     returns com.zdsoft.webservice.namespace.userservice.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://webservice.zdsoft.com/namespace/userservice")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://webservice.zdsoft.com/namespace/userservice")
    public User getUser(
        @WebParam(name = "username", targetNamespace = "")
        String username);

}
